### ISSUE TITLE
parallel map that doesn't wait for data to finish before continuing (out of order)

### ISSUE THREAD

**Issue by matthewmueller** [juliangruber/co-stream#14]
Looking to do the following:

1. pass in a bunch of file paths
2. map over each file to read it's contents
3. **attach meta data to each file as they finish (out of order)**
4. collect the files

Basically wondering how to pull off step 3, without waiting for all the contents to be read in the map

**Comment by matthewmueller** [comment]
haha on second thought, i guess i could just do this within the map stream, but wondering if there's a more generic way

**Comment by juliangruber** [comment]
what kind of parallel map implementation are you using? or is it just the co `yield [task1, task2]` stuff?

**Comment by matthewmueller** [comment]
got it :-) 

i needed a map that took an array and ran it in parallel against set of functions that ran each value in a sequence:

```js
function pmap () {
  let fns = sliced(arguments)
  let concurrency = Infinity

  if (typeof fns[fns.length - 1] !== 'function') {
    concurrency = fns.pop()
  }

  return function (read) {
    return function * (end) {
      let n = concurrency
      let buf = []
      let chunk

      while (n-- && (chunk = yield read(end))) {
        buf = buf.concat(chunk)
      }

      if (!buf.length) return

      return yield buf.map(function * (v) {
        for (fn of fns) v = yield fn(identity(v))
        return v
      })
    }
  }
}
```

**Comment by juliangruber** [comment]
fck yeeeah!
